package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblAttributeDefVal generated by hbm2java
 */
public class TblAttributeDefVal implements java.io.Serializable {

	private int valueId;
	private int attributeId;
	private String valueText;
	private short status;

	public TblAttributeDefVal() {
	}

	public TblAttributeDefVal(int valueId, int attributeId, String valueText,
			short status) {
		this.valueId = valueId;
		this.attributeId = attributeId;
		this.valueText = valueText;
		this.status = status;
	}

	public int getValueId() {
		return this.valueId;
	}

	public void setValueId(int valueId) {
		this.valueId = valueId;
	}

	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

}
