package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblAttributeValue generated by hbm2java
 */
public class TblAttributeValue implements java.io.Serializable {

	private int attrValueId;
	private TblPoi tblPoi;
	private int attrDefId;
	private Integer intValue;
	private String textValue;
	private Integer valueId;

	public TblAttributeValue() {
	}

	public TblAttributeValue(int attrValueId, TblPoi tblPoi, int attrDefId) {
		this.attrValueId = attrValueId;
		this.tblPoi = tblPoi;
		this.attrDefId = attrDefId;
	}

	public TblAttributeValue(int attrValueId, TblPoi tblPoi, int attrDefId,
			Integer intValue, String textValue, Integer valueId) {
		this.attrValueId = attrValueId;
		this.tblPoi = tblPoi;
		this.attrDefId = attrDefId;
		this.intValue = intValue;
		this.textValue = textValue;
		this.valueId = valueId;
	}

	public int getAttrValueId() {
		return this.attrValueId;
	}

	public void setAttrValueId(int attrValueId) {
		this.attrValueId = attrValueId;
	}

	public TblPoi getTblPoi() {
		return this.tblPoi;
	}

	public void setTblPoi(TblPoi tblPoi) {
		this.tblPoi = tblPoi;
	}

	public int getAttrDefId() {
		return this.attrDefId;
	}

	public void setAttrDefId(int attrDefId) {
		this.attrDefId = attrDefId;
	}

	public Integer getIntValue() {
		return this.intValue;
	}

	public void setIntValue(Integer intValue) {
		this.intValue = intValue;
	}

	public String getTextValue() {
		return this.textValue;
	}

	public void setTextValue(String textValue) {
		this.textValue = textValue;
	}

	public Integer getValueId() {
		return this.valueId;
	}

	public void setValueId(Integer valueId) {
		this.valueId = valueId;
	}

}
