package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblCity generated by hbm2java
 */
public class TblCity implements java.io.Serializable {

	private int cityId;
	private String cityName;
	private Set tblDistricts = new HashSet(0);

	public TblCity() {
	}

	public TblCity(int cityId, String cityName) {
		this.cityId = cityId;
		this.cityName = cityName;
	}

	public TblCity(int cityId, String cityName, Set tblDistricts) {
		this.cityId = cityId;
		this.cityName = cityName;
		this.tblDistricts = tblDistricts;
	}

	public int getCityId() {
		return this.cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}

	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	public Set getTblDistricts() {
		return this.tblDistricts;
	}

	public void setTblDistricts(Set tblDistricts) {
		this.tblDistricts = tblDistricts;
	}

}
