package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblConversation generated by hbm2java
 */
public class TblConversation implements java.io.Serializable {

	private int conversationId;
	private TblSubscriber tblSubscriber;
	private String subject;
	private String body;
	private Integer category;
	private Date dateStarted;
	private short status;
	private Integer cityId;
	private Integer districtId;
	
	
	public TblConversation() {
	}

	public TblConversation(int conversationId, TblSubscriber tblSubscriber,
			String subject, String body, Date dateStarted, short status) {
		this.conversationId = conversationId;
		this.tblSubscriber = tblSubscriber;
		this.subject = subject;
		this.body = body;
		this.dateStarted = dateStarted;
		this.status = status;
	}

	public TblConversation(int conversationId, TblSubscriber tblSubscriber,
			String subject, String body, Integer category, Date dateStarted,
			short status) {
		this.conversationId = conversationId;
		this.tblSubscriber = tblSubscriber;
		this.subject = subject;
		this.body = body;
		this.category = category;
		this.dateStarted = dateStarted;
		this.status = status;
	}

	public int getConversationId() {
		return this.conversationId;
	}

	public void setConversationId(int conversationId) {
		this.conversationId = conversationId;
	}

	public TblSubscriber getTblSubscriber() {
		return this.tblSubscriber;
	}

	public void setTblSubscriber(TblSubscriber tblSubscriber) {
		this.tblSubscriber = tblSubscriber;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Integer getCategory() {
		return this.category;
	}

	public void setCategory(Integer category) {
		this.category = category;
	}

	public Date getDateStarted() {
		return this.dateStarted;
	}

	public void setDateStarted(Date dateStarted) {
		this.dateStarted = dateStarted;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public Integer getDistrictId() {
		return districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	

}
