package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblDistrict generated by hbm2java
 */
public class TblDistrict implements java.io.Serializable {

	private int districtId;
	private TblCity tblCity;	
	private int cityId;
	private String districtName;
	private Set tblSubdistricts = new HashSet(0);
	private Set tblPois = new HashSet(0);

	public TblDistrict() {
	}

	public TblDistrict(int districtId, TblCity tblCity, String districtName) {
		this.districtId = districtId;
		this.tblCity = tblCity;
		this.districtName = districtName;
	}

	public TblDistrict(int districtId, TblCity tblCity, String districtName,
			Set tblPois) {
		this.districtId = districtId;
		this.tblCity = tblCity;
		this.districtName = districtName;
		this.tblPois = tblPois;
	}

	public int getDistrictId() {
		return this.districtId;
	}

	public Set getTblSubdistricts() {
		return tblSubdistricts;
	}

	public void setTblSubdistricts(Set tblSubdistricts) {
		this.tblSubdistricts = tblSubdistricts;
	}

	public void setDistrictId(int districtId) {
		this.districtId = districtId;
	}

	public TblCity getTblCity() {
		return this.tblCity;
	}

	public void setTblCity(TblCity tblCity) {
		this.tblCity = tblCity;
	}

	public String getDistrictName() {
		return this.districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName;
	}

	public Set getTblPois() {
		return this.tblPois;
	}

	public void setTblPois(Set tblPois) {
		this.tblPois = tblPois;
	}

	public int getCityId() {
		return cityId;
	}

	public void setCityId(int cityId) {
		this.cityId = cityId;
	}
	
	

}
