package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblFriendshipId generated by hbm2java
 */
public class TblFriendshipId implements java.io.Serializable {

	private int initiatorId;
	private int friendId;
	private short status;

	public TblFriendshipId() {
	}

	public TblFriendshipId(int initiatorId, int friendId, short status) {
		this.initiatorId = initiatorId;
		this.friendId = friendId;
		this.status = status;
	}

	public int getInitiatorId() {
		return this.initiatorId;
	}

	public void setInitiatorId(int initiatorId) {
		this.initiatorId = initiatorId;
	}

	public int getFriendId() {
		return this.friendId;
	}

	public void setFriendId(int friendId) {
		this.friendId = friendId;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblFriendshipId))
			return false;
		TblFriendshipId castOther = (TblFriendshipId) other;

		return (this.getInitiatorId() == castOther.getInitiatorId())
				&& (this.getFriendId() == castOther.getFriendId())
				&& (this.getStatus() == castOther.getStatus());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInitiatorId();
		result = 37 * result + this.getFriendId();
		result = 37 * result + this.getStatus();
		return result;
	}

}
