package com.persona.kg.dao;

import com.persona.kg.common.ApplicationConstants;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblImage generated by hbm2java
 */
public class TblImage implements java.io.Serializable {

	private int imageId;
	private TblSubscriber tblSubscriber;
	private short status;
	private int imgType;
	private String filename;


	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public TblImage() {
	}

	public TblImage(int imageId, TblSubscriber tblSubscriber, short status,
			int imgType) {
		this.imageId = imageId;
		this.tblSubscriber = tblSubscriber;
		this.status = status;
		this.imgType = imgType;
	}

	public int getImageId() {
		return this.imageId;
	}

	public void setImageId(int imageId) {
		this.imageId = imageId;
	}

	public TblSubscriber getTblSubscriber() {
		return this.tblSubscriber;
	}

	public void setTblSubscriber(TblSubscriber tblSubscriber) {
		this.tblSubscriber = tblSubscriber;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	public int getImgType() {
		return this.imgType;
	}

	public void setImgType(int imgType) {
		this.imgType = imgType;
	}
	
	public String getThumbnail(){
		StringBuilder builder=new StringBuilder();
		builder.append(ApplicationConstants.getImageUrl()).append("thumb_").append(filename.substring(0,filename.indexOf("."))).append(".png");
		return builder.toString();
	}
	
	public String getImageUrl(){
		StringBuilder builder=new StringBuilder();
		builder.append(ApplicationConstants.getImageUrl()).append(filename);
		return builder.toString();
	}

}
