package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblLandingPage generated by hbm2java
 */
public class TblLandingPage implements java.io.Serializable {

	private Integer lpid;
	private String userIp;
	private String email;
	private Integer action;
	private Date actionDate;
	private String poiType;
	private String comment;

	public TblLandingPage() {
	}

	public TblLandingPage(String userIp) {
		this.userIp = userIp;
	}

	public TblLandingPage(String userIp, String email, Integer action,
			Date actionDate, String poiType, String comment) {
		this.userIp = userIp;
		this.email = email;
		this.action = action;
		this.actionDate = actionDate;
		this.poiType = poiType;
		this.comment = comment;
	}

	public Integer getLpid() {
		return this.lpid;
	}

	public void setLpid(Integer lpid) {
		this.lpid = lpid;
	}

	public String getUserIp() {
		return this.userIp;
	}

	public void setUserIp(String userIp) {
		this.userIp = userIp;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getAction() {
		return this.action;
	}

	public void setAction(Integer action) {
		this.action = action;
	}

	public Date getActionDate() {
		return this.actionDate;
	}

	public void setActionDate(Date actionDate) {
		this.actionDate = actionDate;
	}

	public String getPoiType() {
		return this.poiType;
	}

	public void setPoiType(String poiType) {
		this.poiType = poiType;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
