package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TblList generated by hbm2java
 */
public class TblList implements java.io.Serializable {

	private int listId;
	private TblSubscriber tblSubscriber;
	private String listName;
	private short status;
	private Set tblListItemses = new HashSet(0);

	public TblList() {
	}

	public TblList(int listId, TblSubscriber tblSubscriber, String listName,
			short status) {
		this.listId = listId;
		this.tblSubscriber = tblSubscriber;
		this.listName = listName;
		this.status = status;
	}

	public TblList(int listId, TblSubscriber tblSubscriber, String listName,
			short status, Set tblListItemses) {
		this.listId = listId;
		this.tblSubscriber = tblSubscriber;
		this.listName = listName;
		this.status = status;
		this.tblListItemses = tblListItemses;
	}

	public int getListId() {
		return this.listId;
	}

	public void setListId(int listId) {
		this.listId = listId;
	}

	public TblSubscriber getTblSubscriber() {
		return this.tblSubscriber;
	}

	public void setTblSubscriber(TblSubscriber tblSubscriber) {
		this.tblSubscriber = tblSubscriber;
	}

	public String getListName() {
		return this.listName;
	}

	public void setListName(String listName) {
		this.listName = listName;
	}

	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	public Set getTblListItemses() {
		return this.tblListItemses;
	}

	public void setTblListItemses(Set tblListItemses) {
		this.tblListItemses = tblListItemses;
	}

}
