package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblLandingPagePoi generated by hbm2java
 */
public class TblLandingPagePoi implements java.io.Serializable {

	private Integer lpid;
	private String poiType;
	private String comment;
	private String image;
	private String username;
	private String password;

	public TblLandingPagePoi() {
	}

	public TblLandingPagePoi(String poiType, String comment, String image,
			String username, String password) {
		this.poiType = poiType;
		this.comment = comment;
		this.image = image;
		this.username = username;
		this.password = password;
	}

	public Integer getLpid() {
		return this.lpid;
	}

	public void setLpid(Integer lpid) {
		this.lpid = lpid;
	}

	public String getPoiType() {
		return this.poiType;
	}

	public void setPoiType(String poiType) {
		this.poiType = poiType;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
