package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblListItems generated by hbm2java
 */
public class TblListItems implements java.io.Serializable {

	private int itemId;
	private TblList tblList;
	private TblPoi tblPoi;
	private Short order;

	public TblListItems() {
	}

	public TblListItems(int itemId, TblList tblList) {
		this.itemId = itemId;
		this.tblList = tblList;
	}

	public TblListItems(int itemId, TblList tblList, TblPoi tblPoi, Short order) {
		this.itemId = itemId;
		this.tblList = tblList;
		this.tblPoi = tblPoi;
		this.order = order;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public TblList getTblList() {
		return this.tblList;
	}

	public void setTblList(TblList tblList) {
		this.tblList = tblList;
	}

	public TblPoi getTblPoi() {
		return this.tblPoi;
	}

	public void setTblPoi(TblPoi tblPoi) {
		this.tblPoi = tblPoi;
	}

	public Short getOrder() {
		return this.order;
	}

	public void setOrder(Short order) {
		this.order = order;
	}

}
