package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblNotification generated by hbm2java
 */
public class TblNotification implements java.io.Serializable {

	private int notificationId;
	private String notificationText;
	private short notificationType;
	private int senderId;
	private Date notificationDate;

	public TblNotification() {
	}

	public TblNotification(int notificationId, String notificationText,
			short notificationType, int senderId, Date notificationDate) {
		this.notificationId = notificationId;
		this.notificationText = notificationText;
		this.notificationType = notificationType;
		this.senderId = senderId;
		this.notificationDate = notificationDate;
	}

	public int getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(int notificationId) {
		this.notificationId = notificationId;
	}

	public String getNotificationText() {
		return this.notificationText;
	}

	public void setNotificationText(String notificationText) {
		this.notificationText = notificationText;
	}

	public short getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(short notificationType) {
		this.notificationType = notificationType;
	}

	public int getSenderId() {
		return this.senderId;
	}

	public void setSenderId(int senderId) {
		this.senderId = senderId;
	}

	public Date getNotificationDate() {
		return this.notificationDate;
	}

	public void setNotificationDate(Date notificationDate) {
		this.notificationDate = notificationDate;
	}

}
