package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblPoiCategoryId generated by hbm2java
 */
public class TblPoiCategoryId implements java.io.Serializable {

	private int poiId;
	private int categoryId;

	public TblPoiCategoryId() {
	}

	public TblPoiCategoryId(int poiId, int categoryId) {
		this.poiId = poiId;
		this.categoryId = categoryId;
	}

	public int getPoiId() {
		return this.poiId;
	}

	public void setPoiId(int poiId) {
		this.poiId = poiId;
	}

	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TblPoiCategoryId))
			return false;
		TblPoiCategoryId castOther = (TblPoiCategoryId) other;

		return (this.getPoiId() == castOther.getPoiId())
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPoiId();
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
