package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblPoiCategory generated by hbm2java
 */
public class TblPoiCategory implements java.io.Serializable {

	private TblPoiCategoryId id;
	private TblPoi tblPoi;
	private TblCategory tblCategory;

	public TblPoiCategory() {
	}

	public TblPoiCategory(TblPoiCategoryId id, TblPoi tblPoi,
			TblCategory tblCategory) {
		this.id = id;
		this.tblPoi = tblPoi;
		this.tblCategory = tblCategory;
	}

	public TblPoiCategoryId getId() {
		return this.id;
	}

	public void setId(TblPoiCategoryId id) {
		this.id = id;
	}

	public TblPoi getTblPoi() {
		return this.tblPoi;
	}

	public void setTblPoi(TblPoi tblPoi) {
		this.tblPoi = tblPoi;
	}

	public TblCategory getTblCategory() {
		return this.tblCategory;
	}

	public void setTblCategory(TblCategory tblCategory) {
		this.tblCategory = tblCategory;
	}

}
