package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * TblPoiAdministrator generated by hbm2java
 */
public class TblPoiAdministrator implements java.io.Serializable {

	private int poiId;
	private TblSubscriber tblSubscriber;
	private TblPoi tblPoi;
	private Boolean isPrimary;
	private short status;
	
	public TblPoiAdministrator() {
	}

	public TblPoiAdministrator(TblSubscriber tblSubscriber, TblPoi tblPoi) {
		this.tblSubscriber = tblSubscriber;
		this.tblPoi = tblPoi;
	}

	public TblPoiAdministrator(TblSubscriber tblSubscriber, TblPoi tblPoi,
			Boolean isPrimary) {
		this.tblSubscriber = tblSubscriber;
		this.tblPoi = tblPoi;
		this.isPrimary = isPrimary;
	}

	public int getPoiId() {
		return this.poiId;
	}

	public void setPoiId(int poiId) {
		this.poiId = poiId;
	}

	public TblSubscriber getTblSubscriber() {
		return this.tblSubscriber;
	}

	public void setTblSubscriber(TblSubscriber tblSubscriber) {
		this.tblSubscriber = tblSubscriber;
	}

	public TblPoi getTblPoi() {
		return this.tblPoi;
	}

	public void setTblPoi(TblPoi tblPoi) {
		this.tblPoi = tblPoi;
	}

	public Boolean getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(Boolean isPrimary) {
		this.isPrimary = isPrimary;
	}

	public short getStatus() {
		return status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

}
