package com.persona.kg.dao;

// Generated 24-Nov-2012 13:57:31 by Hibernate Tools 3.4.0.CR1

/**
 * TblRate generated by hbm2java
 */
public class TblRate implements java.io.Serializable {

	private Integer rateId;
	private int rateType;
	private String additionalComment;
	private int itemId;
	private int ownerId;

	public TblRate() {
	}

	public TblRate(int rateType, int itemId, int ownerId) {
		this.rateType = rateType;
		this.itemId = itemId;
		this.ownerId = ownerId;
	}

	public TblRate(int rateType, String additionalComment, int itemId,
			int ownerId) {
		this.rateType = rateType;
		this.additionalComment = additionalComment;
		this.itemId = itemId;
		this.ownerId = ownerId;
	}

	public Integer getRateId() {
		return this.rateId;
	}

	public void setRateId(Integer rateId) {
		this.rateId = rateId;
	}

	public int getRateType() {
		return this.rateType;
	}

	public void setRateType(int rateType) {
		this.rateType = rateType;
	}

	public String getAdditionalComment() {
		return this.additionalComment;
	}

	public void setAdditionalComment(String additionalComment) {
		this.additionalComment = additionalComment;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public int getOwnerId() {
		return this.ownerId;
	}

	public void setOwnerId(int ownerId) {
		this.ownerId = ownerId;
	}

}
