package com.persona.kg.dao;

import java.util.HashSet;
import java.util.Set;
// Generated Dec 6, 2012 6:25:50 PM by Hibernate Tools 3.1.0.beta4



/**
 * TblSubdistrict generated by hbm2java
 */

public class TblSubdistrict  implements java.io.Serializable {


    // Fields    

     private int subdistrictId;
     private int districtId;
     private String subdistrictName;
     private Set tblPois = new HashSet(0);


    // Constructors

    /** default constructor */
    public TblSubdistrict() {
    }

    /** full constructor */
    public TblSubdistrict(int subdistrictId, TblDistrict tblDistrict, String subdistrictName) {
        this.subdistrictId = subdistrictId;
        
        this.subdistrictName = subdistrictName;
    }
    
	public TblSubdistrict(int subdistrictId, TblDistrict tblDistrict, String subdistrictName,
			Set tblPois) {
        this.subdistrictId = subdistrictId;
       
        this.subdistrictName = subdistrictName;
		this.tblPois = tblPois;
	}
    // Property accessors

    public int getSubdistrictId() {
        return this.subdistrictId;
    }
    
    public void setSubdistrictId(int subdistrictId) {
        this.subdistrictId = subdistrictId;
    }



    

	public String getSubdistrictName() {
        return this.subdistrictName;
    }
    
    public void setSubdistrictName(String subdistrictName) {
        this.subdistrictName = subdistrictName;
    }

	public Set getTblPois() {
		return tblPois;
	}

	public void setTblPois(Set tblPois) {
		this.tblPois = tblPois;
	}

	public int getDistrictId() {
		return districtId;
	}

	public void setDistrictId(int districtId) {
		this.districtId = districtId;
	}

}
