package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblStats generated by hbm2java
 */
public class TblStats implements java.io.Serializable {

	private int statId;
	private TblSubscriber tblSubscriber;
	private int itemId;
	private short actionType;
	private Date dateAdded;
	private short itemType;
	private String log;

	public TblStats() {
	}

	public TblStats(int statId, int itemId, short actionType, Date dateAdded,
			short itemType) {
		this.statId = statId;
		this.itemId = itemId;
		this.actionType = actionType;
		this.dateAdded = dateAdded;
		this.itemType = itemType;
	}

	public TblStats(int statId, TblSubscriber tblSubscriber, int itemId,
			short actionType, Date dateAdded, short itemType) {
		this.statId = statId;
		this.tblSubscriber = tblSubscriber;
		this.itemId = itemId;
		this.actionType = actionType;
		this.dateAdded = dateAdded;
		this.itemType = itemType;
	}

	public int getStatId() {
		return this.statId;
	}

	public void setStatId(int statId) {
		this.statId = statId;
	}

	public TblSubscriber getTblSubscriber() {
		return this.tblSubscriber;
	}

	public void setTblSubscriber(TblSubscriber tblSubscriber) {
		this.tblSubscriber = tblSubscriber;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public short getActionType() {
		return this.actionType;
	}

	public void setActionType(short actionType) {
		this.actionType = actionType;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public short getItemType() {
		return this.itemType;
	}

	public void setItemType(short itemType) {
		this.itemType = itemType;
	}

	public String getLog() {
		return log;
	}

	public void setLog(String log) {
		this.log = log;
	}

}
