package com.persona.kg.dao;

// Generated Jul 22, 2012 7:33:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * TblWatchList generated by hbm2java
 */
public class TblWatchList implements java.io.Serializable {

	private int watchListId;
	private TblSubscriber tblSubscriber;
	private short itemType;
	private int itemId;
	private Date dateAdded;

	public TblWatchList() {
	}

	public TblWatchList(int watchListId, TblSubscriber tblSubscriber,
			short itemType, int itemId) {
		this.watchListId = watchListId;
		this.tblSubscriber = tblSubscriber;
		this.itemType = itemType;
		this.itemId = itemId;
	}

	public TblWatchList(int watchListId, TblSubscriber tblSubscriber,
			short itemType, int itemId, Date dateAdded) {
		this.watchListId = watchListId;
		this.tblSubscriber = tblSubscriber;
		this.itemType = itemType;
		this.itemId = itemId;
		this.dateAdded = dateAdded;
	}

	public int getWatchListId() {
		return this.watchListId;
	}

	public void setWatchListId(int watchListId) {
		this.watchListId = watchListId;
	}

	public TblSubscriber getTblSubscriber() {
		return this.tblSubscriber;
	}

	public void setTblSubscriber(TblSubscriber tblSubscriber) {
		this.tblSubscriber = tblSubscriber;
	}

	public short getItemType() {
		return this.itemType;
	}

	public void setItemType(short itemType) {
		this.itemType = itemType;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

}
